name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: bobbymannino/github-release-action@v1
